### ISSUE TITLE
grcat hangs when using replace

### ISSUE THREAD

**Issue by Jeansen** [garabik/grc#103] opened 2018-07-16 09:02 UTC
I have a log file in which I would like to replace `,` with `\n,` .

So, I put the following in a configuration file my.config:

```
regexp=(,)
replace=\n,
```
and call it like `grcat my.config < some_logifle`.

But this only results in high cpu load and grcat does not respond. I have to kill the process by force.

This also happens with things like:

```
regexp=,
replace=\n,
```
or:

```
regexp=(,)
replace=\1\n
```
or simply:

```
regexp=(,)
replace=\1
```
This works, though:

```
regexp=(,)
replace=\n
```

`python --version` gives me:
Python 2.7.15

**Comment by garabik** [comment] 2018-12-25 19:30
It is clear why this happens - the replacement contains comma, so the regular expression matches the line again, replaces the comma with `\n,`, matches again, replaces the comma again to obtain `\n\n,`, etc... Eventually the python interpreter would run out of memory.

This is by design, replacement does not advance the position in the line, so that any subsequent colourifying rules/matches can be applied against the new line.

In ae79db506e7631ab2ab9cb3193cfbdbb1a4f18fa I have applied a change that stops replacing after the first successful replace, so it should be fixed.

**Closed by garabik** 2018-12-25 19:30 UTC

**Comment by Jeansen** [comment] 2018-12-26 10:59
Oh, great. I will check it out, soon. Thanks!
